### ISSUE TITLE
reduce hard-coded CSS

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-table#483]
Originally from https://community.plot.ly/t/datatable-formatting-issue-width/25133

Instead of things like
```css
.dash-spreadsheet.dash-freeze-left {
    max-width: 500px;
}
```

What if we allowed
```py
fixed_columns={'headers': True, 'data': 1, 'style': {'maxWidth': '800px'}}
```

where `{'maxWidth': '500px'}` is simply the default for (or merged into) `fixed_columns.style`?

Not sure what else fits that pattern - looks like `fixed_rows` has a similar issue, and potentially some other stuff in `Table.less`...
