### ISSUE TITLE
[Feature Request] Facilitate visual customization

### ISSUE THREAD

**Issue by Batalex** [plotly/dash-table#638]
Hi,

dash_table is trully a great addition to the library and there already are several issues on this matter such as https://github.com/plotly/dash-table/issues/483 but I would like this one to be broader.

I am well aware that designing a spreadsheet component is quite complex but here are a few thoughts:

- This component uses inline styles which makes it harder than it needs to be to style a table with css files rather than directly in the Python code. This specific point is quite common in the dash_core_component library by the way.
- Is there any way to have a fully unstyled datatable? e.g. to no load the base css with pink icons
- What could we do to allow users to customize even further the UI: place the export button bellow the table, place the sorting arrows on the right of a column rather than on the left, etc. ?

**Comment by kismsu** [comment]
+1

**Comment by Batalex** [comment]
To be fair, it is quite easy to achieve a custom look using a bit of additional css:
![image](https://user-images.githubusercontent.com/11004857/92356918-34abb000-f0e7-11ea-9c2e-5ccc50cecd2e.png)

`flex-direction` does wonders:

```css
table tr th div {
    display: flex;
    flex-direction: row-reverse;
    justify-content: space-between;
}
table tr th div span.column-header-name {
    margin-right: auto;
}
```
