### ISSUE TITLE
Infinite horizontal scroll with fixed columns

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#795]
See example in https://dash.plotly.com/datatable/width

![horizontal-scroll-regression](https://user-images.githubusercontent.com/1280389/84959064-7bbf7180-b0b3-11ea-9e60-b77236a5411e.gif)

(Firefox)

This is an issue in dash 1.12.0 & 1.13.0. Not sure about earlier versions.

**Comment by mclarty3** [comment]
Hi, I'm facing this same issue with Dash 2 (also only in Firefox, Chrome works fine). Has there been any progress on investigating this? Trying to get around it with CSS styling but having some trouble.

**Comment by mclarty3** [comment]
Just to follow up, I did find a CSS workaround, although it's not super ideal. I removed the fixed column, then manually set each cell in column 0 to sticky. To get a border for the column, I added a ::before and an ::after pseudo-element to each cell in column 0 and gave it a border.

```css
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner td.dash-cell.column-0,
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner th.dash-header.column-0 {
	background-color: white !important;
	position: sticky;
	left: 0;
}

.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner th.dash-header.column-0::before,
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner th.dash-header.column-0::after,
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner td.dash-cell.column-0::before,
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner td.dash-cell.column-0::after {
	content: '';
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	border-right: 1px solid #EEEEF1;
}
```
